services:
  db:
    image: postgres:15-alpine
    container_name: evoting-db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: evoting-backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data: