services:
  db:
    image: postgres:15-alpine
    container_name: evoting-db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: evoting-backend
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis   # <- add Redis dependency
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  nginx:
    image: nginx:alpine
    container_name: evoting-nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - backend

  redis:   # <- new Redis service
    image: redis:7-alpine
    container_name: evoting-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  static_volume:
  media_volume: