# Generated by Django 5.1.3 on 2026-02-07 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="candidate",
            old_name="name",
            new_name="full_name",
        ),
        migrations.RenameField(
            model_name="position",
            old_name="name",
            new_name="title",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="manifesto",
        ),
        migrations.AddField(
            model_name="candidate",
            name="party",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="candidates/"),
        ),
        migrations.AddField(
            model_name="election",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Vote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("voted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="elections.candidate",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
