# Generated by Django 5.1.3 on 2026-02-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_rename_name_candidate_full_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="position",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elections.position",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("voter", "position")},
        ),
    ]
