# Generated by Django 5.1.3 on 2026-02-21 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0004_politicalparty_alter_candidate_party"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
