# Generated by Django 5.1.3 on 2026-02-22 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0005_election_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="vote",
            name="election",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="elections.election",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vote",
            name="status",
            field=models.CharField(
                choices=[("valid", "Valid"), ("invalid", "Invalid")],
                default="valid",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
