# Generated by Django 5.1.3 on 2026-01-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_voted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="national_id",
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
