# Generated by Django 5.1.3 on 2026-02-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_has_voted_user_national_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="has_voted",
            field=models.BooleanField(
                default=False,
                help_text="Has the voter already voted in the current election?",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="national_id",
            field=models.CharField(
                help_text="Simulated National ID / Voter ID", max_length=20, unique=True
            ),
        ),
    ]
