# Generated by Django 5.1.3 on 2026-02-19 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_vote_position_alter_vote_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="PoliticalParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("abbreviation", models.CharField(blank=True, max_length=20)),
                ("badge", models.ImageField(upload_to="party_badges/")),
            ],
        ),
        migrations.AlterField(
            model_name="candidate",
            name="party",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="elections.politicalparty",
            ),
        ),
    ]
